import "app/styles/globals.css";

import { Electrolize, } from "next/font/google";

import { TRPCReactProvider } from "app/trpc/react";
import { ConfigProvider } from "antd";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const electrolize = Electrolize({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={electrolize.className}>
        <ConfigProvider
          theme={{
            token: {
              fontFamily: electrolize.style.fontFamily,
            },
          }}
        >
          <AntdRegistry>
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </AntdRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
